services:
  db:
    image: postgres:16
    container_name: job-tracker-db
    environment:
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpass
      POSTGRES_DB: job_tracker
    ports:
      - "5432:5432"
    volumes:
      - job-tracker-db-data:/var/lib/postgresql/data

volumes:
  job-tracker-db-data: